### ISSUE TITLE
Exception class not found in WebflowException

### ISSUE THREAD

**Issue by brianium** [expertlead/webflow-php-sdk#1]
Thanks so much for this SDK. Just encountered an error while using this - the `WebflowException` class extends `Exception` and this generates a fatal error when an attempt to throw `WebflowException` is made.

I think this is as simple as adding a `use Exception` statement to that file - or escaping `Exception` as `\Exception`

**Comment by wivern-co-uk** [comment]
Thanks for reporting @brianium, will merge PR by @johncorrelli soon, just want to add some CI so we can have tests up and running.

**Comment by wivern-co-uk** [comment]
Fixed in version 0.0.6
https://packagist.org/packages/expertlead/webflow-php-sdk#0.0.6
