### ISSUE TITLE
What type of array the updateItem function required?

### ISSUE THREAD

**Issue by oksr** [expertlead/webflow-php-sdk#4]

**Comment by oksr** [comment]
anyone ? 
i have success to create an item but not to update one,
I'm kind of beginner in PHP,  would love to get help with that issue
thanks

**Comment by wivern-co-uk** [comment]
Hi @ofekseroussi,

I assume that's the same question you are raising at forum https://forum.webflow.com/t/php-sdk-for-the-webflow-cms-api/76883/1

Could you please provide a sample of your code which is not working in this thread, so it's easier to help you? 

Generally, to make update work you need to specify itemId which you want to alter. As you can see from source, method expects `collectionId` and `itemId`, along with `fields` array.
https://github.com/expertlead/webflow-php-sdk/blob/master/src/Webflow/Api.php#L174

**Comment by oksr** [comment]
Hey! Thanks for the response 
Here’s a sample of my code :

`<?php
require_once __DIR__ . '/vendor/autoload.php';

$collectionId ="5c3b8cb691db03ac5757c65c";
$itemId = "5c3b8cb691db03fa2057c69e";
$webflow = new \Webflow\Api('e3ed2783864ae36d02f5445736422e3*****************************');
$fields = [
        'name' => 'New item updated via API',
        'kmvt' => 2,
        '_archived' => false,
        '_draft' => false
];
$webflow->updateItem($collectionId, $itemId, $fields);`

**Comment by wivern-co-uk** [comment]
@ofekseroussi can you please also share the details of an error you having, is there any details, but 500 error code?

The assumption is that you have some required fields missed. You can check which fields are required by running:
```php
$collectionDetails = $webflow->collection($collectionId);
```

**Comment by oksr** [comment]
@wivern-co-uk according to `$collectionDetails = $webflow->collection($collectionId);` all the field that required are shown in $fields.. 
<img width="1324" alt="screen shot 2019-01-21 at 19 27 49" src="https://user-images.githubusercontent.com/23171765/51490212-3827e180-1db3-11e9-8e6b-46ebf004c01b.png">

**Comment by oksr** [comment]
Found the problem, i suppoesd to define $fields like that
 `$fields1 = new stdClass();

$fields = [
    'name' => 'New item updated via API',
    'kmvt' => 2,
    'slug' => 'sadna',
    '_archived' => false,
    '_draft' => false
];
$fields1 = [
    'fields' => $fields
];
//var_dump($fields1);
$webflow->updateItem($collectionId, $itemId, $fields1);`

**Comment by wivern-co-uk** [comment]
Hi @ofekseroussi, glad that you nailed it down! 
I would be nice if you can improve the docs and send a pull request, so more people can benefit from your learnings?
